<<<<<<< HEAD
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';

// NEWSLETTER ACTIONS
export const SET_NEWSLETTERS = 'SET_NEWSLETTERS';
export const FETCH_NEWSLETTER_ID = 'FETCH_NEWSLETTER_ID';

// REQUESTS ACTIONS 
export const CHANGE_SELECTED_REQUEST_TYPE = 'CHANGE_SELECTED_REQUEST_TYPE';
export const SET_REQUESTS = 'SET_REQUESTS';

// HEADER
export const UPDATE_HEADER = 'UPDATE_HEADER';
=======
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER'
>>>>>>> e5b6c86b88a1ce58214aa38b2dbc97c9230466f4
